version: '3'

services:
  web: 
    build: fastapi
    ports:
      - 8000:8000
    volumes:
      - ./fastapi:/app
    networks:
      - test-net
  ollama: 
    build: ollama
    ports:
      - 11434:11434
    volumes:
      - test-vol:/app/ollama
    networks:
      - test-net
    entrypoint: ['/usr/bin/bash', '/pull-llama3.sh']

networks:
  test-net:
    driver: bridge

volumes:
  test-vol: 
    driver: local